### ISSUE TITLE
初始化模板报错

### ISSUE THREAD

**Issue by geeker-cmc** [24jieqi/react-native-lidong-template#7]
初始化模板报错，生成了一个空目录
错误提示
⠏ Downloading templateerror Installing pods failed. This doesn't affect project initialization and you can safely proceed.
However, you will need to install pods manually when running iOS, follow additional steps in "Run instructions for iOS" section.

✖ Downloading template
![WechatIMG17](https://github.com/24jieqi/react-native-lidong-template/assets/20188646/2045ca13-4561-4fde-8e02-15526224c515)

**Comment by onlyling** [comment]
目前猜测可能是 react-native-cli 的版本与模板使用的有点差异，模板现在使用 `react-native@0.72.13`，[@react-native-community/cli](https://github.com/react-native-community/cli?tab=readme-ov-file#compatibility) 对应使用 `^11.0.0`，近期把模板升级到最新。

**Comment by geeker-cmc** [comment]
感谢，试了一下确实版本没有对应上的问题，已经解决了。

**Comment by onlyling** [comment]
[next](https://github.com/24jieqi/react-native-lidong-template/tree/next) 分支适配 [0.74.x] 进行中，同时对预设代码进行瘦身。
